### ISSUE TITLE
BadCredentialsException shown to end-user when attempting to use NRDB as Oauth login

### ISSUE THREAD

**Issue by richardjonathonharris** [Null-Signal-Games/netrunnerdb#223]
Hi everyone,

I put in the wrong credentials when attempting to use nrdb to log into [cobr.ai](cobr.ai) (used the lowercase version of my username `ditaki` instead of the proper case (`Ditaki`) which is correct). I received a traceback error instead of something more appropriate to show to end users. Traceback below:

```
Welcome on NetrunnerDB. Please log in to proceed. Your password will remain confidential.

Symfony\Component\Security\Core\Exception\BadCredentialsException: Bad credentials. in 

/home/alsciende/netrunnerdb/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:88 Stack trace: #0 

/home/alsciende/netrunnerdb/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php(145): session_start() #1 

/home/alsciende/netrunnerdb/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php(302): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start()#2 

/home/alsciende/netrunnerdb/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Session.php(249): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->getBag('attributes') #3 

/home/alsciende/netrunnerdb/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Session.php(271): Symfony\Component\HttpFoundation\Session\Session->getBag('attributes') #4 

/home/alsciende/netrunnerdb/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Session.php(73): Symfony\Component\HttpFoundation\Session\Session->getAttributeBag() #5 

/home/alsciende/netrunnerdb/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ContextListener.php(93): Symfony\Component\HttpFoundation\Session\Session->get('_security_oauth...') #6 

/home/alsciende/netrunnerdb/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall.php(83): Symfony\Component\Security\Http\Firewall\ContextListener->handle(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) 

#7

/home/alsciende/netrunnerdb/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall.php(56): Symfony\Component\Security\Http\Firewall->handleRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), Object(Symfony\Component\DependencyInjection\Argument\RewindableGenerator)) 

#8

/home/alsciende/netrunnerdb/vendor/symfony/symfony/src/Symfony/Bundle/SecurityBundle/EventListener/FirewallListener.php(48): Symfony\Component\Security\Http\Firewall->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) 

#9

/home/alsciende/netrunnerdb/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): Symfony\Bundle\SecurityBundle\EventListener\FirewallListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) 

#10 

/home/alsciende/netrunnerdb/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))

 #11 

/home/alsciende/netrunnerdb/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(127): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) 

#12 /home/alsciende/netrunnerdb/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) 

#13 /home/alsciende/netrunnerdb/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 

#14 /home/alsciende/netrunnerdb/web/app.php(19): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))

 #15 {main}
```

The log-in menu was presented normally below the traceback inline with appropriate CSS styling. 

Thanks!

**Comment by x3N1GM4x** [comment]
Example screenshot:
![image](https://user-images.githubusercontent.com/10621139/50680360-63fb4700-0fff-11e9-811b-e64faae81a8d.png)

**Comment by x3N1GM4x** [comment]
The same issue has been logged by users of ABR, as per #222.
